services:
  - type: web
    name: legacy-rescue-kit-api
    runtime: docker
    plan: free
    branch: main
    rootDir: src/Api
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JwtSecret
        value: ThisIsAnExtremelySecureJWTSecretKeyOfAtLeast64CharsLong_1234567890!@#$%^&*()
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: legacy-rescue-db
          property: connectionString    
      - key: FrontendUrl
        value: https://legacy-rescue-kit.vercel.app

databases:
  - name: legacy-rescue-db
    databaseName: legacy_rescue_kit
    user: legacy_user